### ISSUE TITLE
Support nested if

### ISSUE THREAD

**Issue by yeahdongcn** [yeahdongcn/kustohelmize#13]
```yaml
    {{- if .Values.validator.plugin }}
    plugin:
      {{- if .Values.validator.plugin.env }}
      env: {{ toYaml .Values.validator.plugin.env | nindent 8 }}
      {{- end }}
    {{- end }}
```

**Comment by yeahdongcn** [comment]
This is not supported currently, as we stop walking if `processMap` returns true.

**Comment by fishingfly** [comment]
![image](https://github.com/yeahdongcn/kustohelmize/assets/29742631/f52bb42c-1bc1-4301-b4c3-5f00e4e3db73)
seems this function is a common function

**Comment by yeahdongcn** [comment]
@fishingfly Feel free to implement this if you have time 🥇
