### ISSUE TITLE
nil pointer haapended when not set globalConfig

### ISSUE THREAD

**Issue by fishingfly** [yeahdongcn/kustohelmize#15]
If I don't set sharedValues ​​and globalConfig, an error will be reported when running `make helm`
![image](https://user-images.githubusercontent.com/29742631/211451019-2f2d78ad-471a-4264-830a-a4e7f4466f91.png)
![image](https://user-images.githubusercontent.com/29742631/211451794-159979ea-125f-4248-bd9f-743bd166cf0b.png)

**Comment by fishingfly** [comment]
There will be a {} in the values.yaml file
![image](https://user-images.githubusercontent.com/29742631/211452170-5a8e9338-c18b-4e91-8a92-2f6ac179fffd.png)

**Comment by yeahdongcn** [comment]
Thanks for the PR!
