### ISSUE TITLE
Add a `control-if` that checks an other variable value

### ISSUE THREAD

**Issue by PierrePIRONIN** [yeahdongcn/kustohelmize#34]
## Issue
Would be nice to have a `control-if` that states on an other variable instead of the same one it would inject.

## Simple example
A `control-if` directive that permits the following snippet
```
{{- if .Values.autoscaling.disable }}
replicas: {{ .Values.replicaCount }}
{{- end }}
```

**Comment by yeahdongcn** [comment]
I’ll take a look at this over the weekend.

**Comment by yeahdongcn** [comment]
@PierrePIRONIN Could you please verify if the output in `0500` directory meets your requirements?"

**Comment by PierrePIRONIN** [comment]
@yeahdongcn it seems good ! Ok for me.

**Comment by yeahdongcn** [comment]
> @yeahdongcn it seems good ! Ok for me.

Great! I've merged it into the main branch. Could you give it a try? Thanks!

**Comment by sathieu** [comment]
Thanks @yeahdongcn.

Can this be documented ?

Could there be the same feature for `control-if-yaml`?

**Comment by yeahdongcn** [comment]
@sathieu Done.

Please see: https://github.com/yeahdongcn/kustohelmize/tree/main/examples#strategies

**Comment by sathieu** [comment]
Thanks @yeahdongcn
